# Generated by Django 5.2.8 on 2025-12-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymodel',
            name='customer_mobile',
            field=models.IntegerField(default=0),
        ),
    ]
