# Generated by Django 5.2.8 on 2025-11-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]
