# Generated by Django 5.2.8 on 2025-11-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_productsmodel_offer_productsmodel_trending'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_desc', models.CharField(max_length=100)),
                ('product_price', models.IntegerField(default=0)),
            ],
        ),
    ]
