# Generated by Django 5.2.8 on 2025-11-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_cartmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='product_image',
            field=models.ImageField(default='default.jpeg', upload_to='uploads'),
        ),
    ]
