# Generated by Django 5.2.8 on 2025-11-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_cartmodel_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='product_category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
