# Generated by Django 5.2.8 on 2025-11-14 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_cartmodel_price_cartmodel_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='price',
            new_name='total_price',
        ),
    ]
